RegisterNUICallback('sunny-job-rangerpark:nui:refresh-player', function(_, cb)
    QbrCore:TriggerCallback("sunny-job-rangerpark:server:get-criminal-records", function(data)
        SendReactMessage('loadCriminalRecords', data)
    end)
    cb({})
end)

RegisterNUICallback('sunny-job-rangerpark:nui:hideFrame', function(_, cb)
    ToggleNuiFrame(false)
    cb({})
end)
